# Player Section
"All Items Examined" = false # default : false
"Armored Rigs" = false # default : false
"Disable Container Restrictions" = false # default : false
"Disable Backpack Restrictions" = false # default : false
"Disable Penalties" = false # default : false
"Disable Malfunctions" = false # default : false
"Weight Modifier" = 1.0 # default : 1.0x
"Scavenger Cooldown" = 1200 # default : 1200 seconds

"Disable Fall Damage" = false # default : false
"Disable Hunger" = false # default : false
"Energy Drain" = 3.2 # default : 3.2
"Hydration Drain" = 2.6 # default : 2.6

# Skill Section

# Bot Section

# Trader Section

# Hideout Section

# InRaid Section

# Weather Section

# AirDrop Section