# * changing any values WILL alter something, so be careful! * #

# Player Section
# / gameplay options
"All Items Examined" = false # default : false
"Armored Rigs" = false # default : false
"Disable Container Restrictions" = false # default : false
"Disable Backpack Restrictions" = false # default : false
"Disable Penalties" = false # default : false
"Disable Malfunctions" = false # default : false
"Scavmode Cooldown" = 1200 # default : 1200 seconds
"Weight Modifier" = 1.0 # default : 1.0x
# / health options
"Disable Fall Damage" = false # default : false
"Disable Hunger" = false # default : false
"Energy Drain" = 3.2 # default : 3.2
"Hydration Drain" = 2.6 # default : 2.6

# Skill Section
# / experience modifiers
"Survived" = 1.3 # default : 1.30
"Killed" = 1.0 # default : 1.0
"Runthru" = 0.5 # default : 0.50
"Headshot" = 1.2 # default : 1.20
# / skill modifiers
"Wep Skill Rate" = 1.0 # default 1.0
"Soft Skill Rate" = 0.4 # default : 0.4
"Disable Skill Fatigue" = false # default : false

# Bot Section
"Usec:Bear" = 50 # default : 50
"Friendly Fire Chance" = 50 # default : 50
"Scav to PMC" = 0 # default : x

# Trader Section
# / flea options
"Flea Level" = 15 # default : 15
"Disable Flea" = false # default : false
"Disable Flea Blacklist" = false # default : false
# / fence options
"Assortment Size" = 100 # default : 100
# / trader options
"Disable Insurance" = false # default : false
"Hybrid Clothing" = false # default : false

# Hideout Section
"Instant Construction" = false # default : false
"Construction Modifier" = 1.0 # default : 1.0
"Instant Production" = false # default : false
"Production Modifier" = 1.0 # default : 1.0

# InRaid Section

# Weather Section

# AirDrop Section