# * changing any values WILL alter something, so be careful! * #

# Player Section
# / gameplay options
"All Items Examined" = false # default : false
"Armored Rigs" = false # default : false
"Disable Container Restrictions" = false # default : false
"Disable Backpack Restrictions" = false # default : false
"Disable Penalties" = false # default : false
"Disable Malfunctions" = false # default : false
"Scavmode Cooldown" = 1200 # default : 1200 seconds
"Weight Modifier" = 1.0 # default : 1.0x
# / health options
"Disable Fall Damage" = false # default : false
"Disable Hunger" = false # default : false
"Energy Drain" = 3.2 # default : 3.2
"Hydration Drain" = 2.6 # default : 2.6

# Skill Section
# / experience modifiers
"Survived" = 1.3 # default : 1.30
"Killed" = 1.0 # default : 1.0
"Runthru" = 0.5 # default : 0.50
"Headshot" = 1.2 # default : 1.20
# / skill modifiers
"Wep Skill Rate" = 1.0 # default 1.0
"Soft Skill Rate" = 0.4 # default : 0.4
"Disable Skill Fatigue" = false # default : false

# Bot Section
"Usec:Bear" = 50 # default : 50
"Friendly Fire Chance" = 50 # default : 50
"Scav to PMC" = 0 # default : x

# Trader Section
# / flea options
"Flea Level" = 15 # default : 15
"Disable Flea" = false # default : false
"Disable Flea Blacklist" = false # default : false
# / fence options
"Assortment Size" = 100 # default : 100
# / trader options
"Disable Insurance" = false # default : false
"Hybrid Clothing" = false # default : false

# Hideout Section
"Instant Construction" = false # default : false
"Construction Modifier" = 1.0 # default : 1.0
"Instant Production" = false # default : false
"Production Modifier" = 1.0 # default : 1.0

# InRaid Section
# / general options
"Consistent Extracts" = false # default : false
# / duration options
"Customs" = 40 # default : 40
"Factory" = 20 # default : 20
"Interchange" = 40 # default : 40
"Labs" = 35 # default : 35
"Reserve" = 40 # default : 40
"Shoreline" = 45 # default : 45
"Woods" = 40 # default : 40
"Lighthouse" = 40 # default : 40
"Streets" = 50 # default : 50
# / reshala options
"Reshala %" = 5 # default : 5
"Reshala Guards" = 4 # default : 4
"Reshala Locations" = "ZoneDormitory,ZoneGasStation" # default : "ZoneDormitory,ZoneGasStation"
"Customs Cultist %" = 2 # default : 2
"Customs Goonsquad %" = 5 # default : 5 / within ZoneScavBase
# / killa options
"Killa %" = 5 # default : 5
        # default : "ZoneCenterBot,ZoneCenter,ZoneOLI,ZoneIDEA,ZoneGoshan,ZoneIDEAPark,ZoneOLIPark"
"Killa Locations" = "ZoneCenterBot,ZoneCenter,ZoneOLI,ZoneIDEA,ZoneGoshan,ZoneIDEAPark,ZoneOLIPark"
# / tagilla options
"Tagilla Day %" = 5 # default : 5
"Tagilla Night %" = 10 # default : 10
"Factory Cultist %" = 2 # default : 2
# / gluhar options
"Gluhar %" = 5 # default : 5
"Gluhar Guards" = [ 2, 2, 2 ] # (t1,t2,t3) default : 2, 2, 2
         # default : "ZoneRailStrorage,ZoneRailStrorage,ZoneRailStrorage,ZonePTOR1,ZonePTOR2,ZoneBarrack,ZoneBarrack,ZoneBarrack,ZoneSubStorage"
"Gluhar Locations" = "ZoneRailStrorage,ZoneRailStrorage,ZoneRailStrorage,ZonePTOR1,ZonePTOR2,ZoneBarrack,ZoneBarrack,ZoneBarrack,ZoneSubStorage"
# / shturman options
"Shturman %" = 5 # default : 5
"Shturman Guards" = 2 # default : 2
"Woods Cultist %" = 3 # default : 3
"Woods Goonsquad %" = 5 # default : 5 / within ZoneScavBase2
# / sanitar options
"Sanitar %" = 5 # default : 5
"Sanitar Guards" = 2 # default : 3
          # default : "ZonePort,ZoneGreenHouses,ZoneSanatorium1,ZoneGreenHouses,ZoneSanatorium2"
"Sanitar Locations" = "ZonePort,ZoneGreenHouses,ZoneSanatorium1,ZoneGreenHouses,ZoneSanatorium2"
"Shoreline Cultist %" = 3 # default : 3
"Shoreline Goonsquad %" = 5 # default : 5 / within ZoneMeteoStation
# / lighthouse options
"Lighthouse Goonsquad %" = 5 # default : 5
"Lighthouse Goonsquad Locations" = "Zone_TreatmentContainers,Zone_Chalet" # default : "Zone_TreatmentContainers,Zone_Chalet"
# / streets options
"STR Gluhar %" = 0.6 # default : 0.60 / within ZoneCarShowroom
"STR Gluhar Guards" = [ 2, 2, 2 ] # (t1,t2,t3) default : 2, 2, 2
"STR Killa %" = 0.6 # default : 0.60 / within ZoneHotel_1/ZoneHotel_2

# AirDrop Section
# / chance options
"ad-customs" = 1.0 # default : 1.0
"ad-woods" = 1.0 # default : 1.0
"ad-lighthouse" = 1.0 # default : 1.0
"ad-shoreline" = 1.0 # default : 1.0
"ad-interchange" = 1.0 # default : 1.0
"ad-reserve" = 1.0 # default : 1.0